//admin
export { default as Login } from "./Admins/Login"
export { default as Dahroash } from "./Admins/Dahroash"
export { default as Category } from './Admins/Category'
export { default as Products } from "./Admins/Products"
export { default as Employee } from "./Admins/Employee"
export { default as Customer } from "./Admins/Customer"
export { default as Myinfo } from "./Admins/Myinfo"
export { default as Comment } from "./Admins/Comment"
export { default as Bills } from "./Admins/Bills"
export { default as Oder } from "./Admins/Oder"
export {default as Feedbacks} from './Admins/Feedbacks'
export {default as ImportCoupon} from './Admins/ImportCoupon'
export {default as ShowCoupon } from "./Admins/ShowCoupon" 
export {default as DetailCoupon} from "./Admins/DetailCoupon"
export {default as ProfitOverTime} from "./Admins/ProfitOverTime"
export {default as ProfitByProduct} from "./Admins/ProfitByProduct"
export {default as ExportPDF} from "./Admins/ExportPDF"
//nhân viên đơn hàng
export {default as LoginShipper} from "./NhanVienDH/LoginShipper"
export {default as Success} from "./NhanVienDH/Success"
export {default as AllOrder} from "./NhanVienDH/AllOrder"
export {default as OrdersDelivered} from"./NhanVienDH/OrdersDelivered"
export {default as OrderDestroy} from "./NhanVienDH/OrderDestroy"
//customer
export { default as Home } from "./Customers/Home"
export { default as ProductsCustomer } from "./Customers/Products"
export { default as Details } from "./Customers/Details"
export { default as Cart } from "./Customers/Cart"
export { default as LoginCustomer } from "./Customers/Login"
export { default as Bill } from "./Customers/Bill"
export { default as RegisterCustomer } from "./Customers/Register"
export { default as Contact } from "./Customers/Contact"
export { default as InfoCustomer } from "./Customers/InfoCustomer"
export { default as ForgotPasswordCustomer } from "./Customers/ForgotPasswordCustomer.js"
export { default as ResetPasswordCustomer } from "./Customers/ResetPassWordCustomer"
export {default as Blog} from "./Customers/Blog"
export {default as Abouts} from "./Customers/Abouts"
export {default as PageNotFound} from "./Customers/PageNotFound"

